# Generated by Django 5.0.6 on 2024-05-13 23:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior a 0'), django.core.validators.MaxValueValidator(5, 'Avaliação não pode ser maior que 5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='video.video')),
            ],
        ),
    ]
