# Generated by Django 5.0.6 on 2024-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
